### PR TITLE
add quotes around file path if it contains spaces

### LINKED ISSUE #5: Does not work when the file path contains spaces
Using extension verison `v1.0.3` and vscode `1.60.1`

log output while running:

```C:\ProgramData\scoop\apps\python\current\python.exe -m doctest -v c:\Users\logonoff\Desktop\i am a folder with spaces\python.py
Traceback (most recent call last):
  File "C:\ProgramData\scoop\apps\python\current\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\scoop\apps\python\current\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\scoop\apps\python\current\lib\doctest.py", line 2793, in <module>
    sys.exit(_test())
  File "C:\ProgramData\scoop\apps\python\current\lib\doctest.py", line 2785, in _test
    failures, _ = testfile(filename, module_relative=False,
  File "C:\ProgramData\scoop\apps\python\current\lib\doctest.py", line 2055, in testfile
    text, filename = _load_testfile(filename, package, module_relative,
  File "C:\ProgramData\scoop\apps\python\current\lib\doctest.py", line 232, in _load_testfile
    with open(filename, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\logonoff\\Desktop\\i'
```

Seems to work when I put quotes around the path to be tested though.

### PR DESCRIPTION
**Pull request by logonoff**
fixes #5 

tested on Windows and works fine, not sure if `getFilePath` function belongs under `ConfigHandler` though

### CODE REVIEW

**Comment by NoahSyn10** [comment]
Looks good, I will have to publish the update and edit the changelogs which might take me a day

**Comment by d3v-null** [comment]
Friendly reminder to have a look at this if you have the time, I ran into the same issue. Thanks :)

**Comment by NoahSyn10** [comment]
> Friendly reminder to have a look at this if you have the time, I ran into the same issue. Thanks :)

Thank you for reminding me! This had completely slipped my mind. I'll get it published after finals this week, I apologize if the bug has been causing you issues.

**Comment by NoahSyn10** [comment]
I made the changes to the currently published code and published the update, I need to majorly refactor the working code and this repository but it should function as is for now. Tag v1.0.4 contains the published version of the code.

**Pull request closed without merging**
